// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXJdAhwnr_PpF_CIzl9NMbTQVHbCh4LZ4',
    appId: '1:108813470924:web:a5a20b6c2e175516550669',
    messagingSenderId: '108813470924',
    projectId: 'examenmobile-955a9',
    authDomain: 'examenmobile-955a9.firebaseapp.com',
    storageBucket: 'examenmobile-955a9.appspot.com',
    measurementId: 'G-FMNLV2KWZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw4z2SxtvqMDClr2kboNZA4VOovVVUR68',
    appId: '1:108813470924:android:22c1cbc4e2f9b1ba550669',
    messagingSenderId: '108813470924',
    projectId: 'examenmobile-955a9',
    storageBucket: 'examenmobile-955a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVrRRZ23yIPP9wjU6xGemcuyS89IdkSTM',
    appId: '1:108813470924:ios:e8c26f09c843b91c550669',
    messagingSenderId: '108813470924',
    projectId: 'examenmobile-955a9',
    storageBucket: 'examenmobile-955a9.appspot.com',
    iosBundleId: 'com.example.examMobile2',
  );
}
